version: '2'
services:
  api:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - cache:/app/tmp/cache
    ports:
      - "3000:3000"
    command: [ sh, -c, "rm -rf /app/tmp/pids/server.pid && yarn install && bundle exec rails s -b 0.0.0.0" ] #removes tmp pids and runs yarn install

    # command: tail -f /dev/null
    # prevents the container from closing
    depends_on:
      - postgres
      - webpack

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password

    volumes:
      - db:/var/lib/postgresql/data

  webpack:
    build: .
    env_file:
      - '.env.docker'
    command: [ sh, -c, "yarn install && ./bin/webpack-dev-server" ]
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - cache:/app/tmp/cache
    ports:
        - '3036:3036'

volumes:
  data:
    driver: local
  node_modules:
    driver: local
  cache:
    driver: local
  db:
    driver: local